# Site Settings
title: gem5
sourceurl: "https://github.com/gem5/new-website/tree/master/"
url: "https://new.gem5.org/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      
# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
  toc_levels: "1,2"

collections:
  pages:
    output: true
