# Site Settings
title: gem5
sourceurl: "https://gem5.googlesource.com/public/gem5-website/+/refs/heads/master/README.md"
url: "https://www.gem5.org/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      
# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
  toc_levels: "1,2"

collections:
  pages:
    output: true
