# Site Settings
title: gem5
sourceurl: "https://github.com/gem5/new-website/tree/master/"
url: "http://localhost:4000"
baseurl: ""

# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
  toc_levels: "1,2"

collections:
  pages:
    output: true
