# Site Settings
title: gem5
baseurl: ""
url: "http://cm-jingwenlow.github.io"

# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM

collections:
  pages:
    output: true
