# Site Settings
title: gem5
sourceurl: "https://github.com/gem5/new-website/tree/master/"
url: "http://gem5.github.io/new-website/"
baseurl: "/new-website"

# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
  toc_levels: "1,2"

collections:
  pages:
    output: true
