# Site Settings
title: gem5
sourceurl: "https://github.com/cm-jingwenlow/cm-jingwenlow.github.io/tree/master/"
url: "http://localhost:4000"

# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
  toc_levels: "1,2"

collections:
  pages:
    output: true
